service: math-and-storage-service

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: ${self:service}-${self:provider.stage}-storage

functions:
  addNumbers:
    handler: src/math/add.handler
    events:
      - http:
          path: math/add
          method: post
          cors: true

  uploadFile:
    handler: src/storage/upload.handler
    events:
      - http:
          path: storage/upload
          method: post
          cors: true

resources:
  Resources:
    StorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

plugins:
  - serverless-offline
