org: rajx02
service: math-and-storage-service

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::r-bucket2025/*

functions:
  addNumbers:
    handler: src/math/add.handler
    events:
      - http:
          path: math/add
          method: post
          cors: true

  uploadFile:
    handler: src/storage/upload.handler
    events:
      - http:
          path: storage/upload
          method: post
          cors: true

plugins:
  - serverless-offline
